version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uisvh8e57vw
      POSTGRES_DB: fable

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uisvh8e57vw
      - POSTGRES_DB=fable

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uisvh8e57vw
      - POSTGRES_DB=fable
    stdin_open: true
    tty: true
    command: go run test/test.go